name: app
type: php:8.1

# Servizi da utilizzare durante la build
build:
    flavor: composer

relationships:
    database: "mysql:mysql"

mounts:
    "/storage": "shared:files/storage"
    "/public/storage": "shared:files/public/storage"

web:
    locations:
        "/":
            root: "public"
            index: ["index.php"]
            passthru: "/index.php"
    commands:
        start: "php artisan serve --host=0.0.0.0 --port=8080"

crons:
    laravel-schedule:
        spec: "*/5 * * * *"
        cmd: "php artisan schedule:run"

hooks:
    build: |
        composer install --prefer-dist --no-progress --no-interaction
    deploy: |
        php artisan migrate --force
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache

disk: 2048
